spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ivy_events_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
storage:
  provider: local   # or s3
  local:
    path: uploads   # where files go in dev
#  s3:
#    bucket: ivyinc-storage
#    region: eu-central-1
#    accessKey: ${AWS_ACCESS_KEY_ID:}
#    secretKey: ${AWS_SECRET_ACCESS_KEY:}

server:
  port: 8081